spring:
  application:
    name: console-services
  datasource:
    url: @jdbc.url@
    username: paywithmybank
    password: paywithmybank
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 7000
  servlet:
    context-path: /console-services

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:7002/discovery/eureka/}
  instance:
    prefer-ip-address: true

