spring:
  application:
    name: console-services
  datasource:
    url: @jdbc.url@
    username: paywithmybank
    password: paywithmybank
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5

