spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
server:
  port: 7003
  servlet:
    context-path: /gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:7002/discovery/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    prometheus:
      enabled: true
