spring:
  application:
    name: gateway

server:
  port: 7003
  servlet:
    context-path: /gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:7002/discovery/eureka/}
  instance:
    prefer-ip-address: true

zuul:
  sensitive-headers: Cookie
