spring:
  application:
    name: configuration
  cloud:
    config:
      name: configuration
      server:
        git:
          uri: file://${user.home}/cloud-git

eureka:
  client:
    region: default
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    eureka-server-port: 7002

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus