spring:
  application:
    name: configuration
  cloud:
    config:
      name: configuration
      server:
        git:
          uri: file://${user.home}/cloud-git

server:
  port: 7001
  servlet:
    context-path: /config

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: @eureka-host@
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    prometheus:
      enabled: true
